### ISSUE TITLE
Problem with example.py

### ISSUE THREAD

**Issue by aakb101** [kyegomez/PALM-E#4]
I'm getting the following error after running the example.py:
`  File "palme/example.py", line 8, in <module>
    model = PalmE()
            ^^^^^^^
  File "palme/palme/model.py", line 122, in __init__
    self.encoder = ViTransformerWrapper(
    ^^^^^^^^^^^^
  File "python3.11/site-packages/torch/nn/modules/module.py", line 1643, in __setattr__
    raise AttributeError(
AttributeError: cannot assign module before Module.__init__() call`

**Comment by aakb101** [comment]
In model.py, super(PalmE).__init__() has to be         super(PalmE, self).__init__() or super().__init__() I guess to fix the aforementioned issue?

**Comment by aakb101** [comment]
There are still other issues with the example you provided in the package.

**Comment by automateyournetwork** [comment]
Same issue here python3 example.py 
Traceback (most recent call last):
  File "/home/johncapobianco/multimodal/example.py", line 8, in <module>
    model = PalmE()
  File "/home/johncapobianco/modal/lib/python3.10/site-packages/palme/model.py", line 122, in __init__
    self.encoder = ViTransformerWrapper(
  File "/home/johncapobianco/modal/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1643, in __setattr__
    raise AttributeError(
AttributeError: cannot assign module before Module.__init__() call

**Comment by kyegomez** [comment]
@zehranrgi its fixed now, it was due to one of the modules of the transformer block I turned it off and it works good now!

We could even try using pretrained clip for img embeds
